name: code-quality

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black==23.1.0 pylint==2.16.2
          pip install -r requirements.txt
      - name: Analysing the code with pylint
        run: |
          black --diff --check $(git ls-files '*.py')
          pylint $(git ls-files '*.py')
